/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BrandIndexRouteImport } from './routes/$brand/index'
import { Route as BrandProductRouteImport } from './routes/$brand/$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/$brand/',
  path: '/$brand/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandProductRoute = BrandProductRouteImport.update({
  id: '/$brand/$product',
  path: '/$brand/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/$brand/$product': typeof BrandProductRoute
  '/$brand/': typeof BrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/$brand/$product': typeof BrandProductRoute
  '/$brand': typeof BrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/$brand/$product': typeof BrandProductRoute
  '/$brand/': typeof BrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/$brand/$product' | '/$brand/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/$brand/$product' | '/$brand'
  id: '__root__' | '/' | '/search' | '/$brand/$product' | '/$brand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  BrandProductRoute: typeof BrandProductRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand/': {
      id: '/$brand/'
      path: '/$brand'
      fullPath: '/$brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand/$product': {
      id: '/$brand/$product'
      path: '/$brand/$product'
      fullPath: '/$brand/$product'
      preLoaderRoute: typeof BrandProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  BrandProductRoute: BrandProductRoute,
  BrandIndexRoute: BrandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
