-- The single `source` URL per product is replaced by one Offer per seller.
ALTER TABLE "Product" DROP COLUMN "source";

-- CreateTable
CREATE TABLE "Seller" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "imageUrl" TEXT,
    "shopUrl" TEXT,

    CONSTRAINT "Seller_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Seller_name_key" ON "Seller"("name");
CREATE UNIQUE INDEX "Seller_slug_key" ON "Seller"("slug");

-- CreateTable
CREATE TABLE "Offer" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "sellerId" TEXT NOT NULL,
    "productUrl" TEXT NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "shippingCost" DECIMAL(10,2),
    "freeShippingFrom" DECIMAL(10,2),
    "inStock" BOOLEAN NOT NULL DEFAULT true,
    "lastCheckedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Offer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Offer_productId_price_idx" ON "Offer"("productId", "price");
CREATE INDEX "Offer_sellerId_idx" ON "Offer"("sellerId");
CREATE UNIQUE INDEX "Offer_productId_sellerId_key" ON "Offer"("productId", "sellerId");

-- Existing price points predate the seller dimension and cannot be attributed
-- to a seller. They are synthetic seed data and are regenerated by `pnpm seed`.
DELETE FROM "PriceHistory";

-- AlterTable
ALTER TABLE "PriceHistory" ADD COLUMN "sellerId" TEXT NOT NULL;
ALTER TABLE "PriceHistory" ADD COLUMN "inStock" BOOLEAN NOT NULL DEFAULT true;

-- CreateIndex
CREATE INDEX "PriceHistory_productId_sellerId_recordedAt_idx" ON "PriceHistory"("productId", "sellerId", "recordedAt");
CREATE UNIQUE INDEX "PriceHistory_productId_sellerId_recordedAt_key" ON "PriceHistory"("productId", "sellerId", "recordedAt");

-- AddForeignKey
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PriceHistory" ADD CONSTRAINT "PriceHistory_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "Seller"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
